version: '3'
services:
  backend:
    image: qnib/plain-zookeeper
    ports:
      - "2181:2181"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
  frontend:
    image: qnib/plain-zkui
    ports:
      - "9090:9090"
    environment:
      - ZK_SERVER=tasks.zookeeper:2181
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
